// generated by stringer -type=StateEnum; DO NOT EDIT

package main

import "fmt"

const _StateEnum_name = "STATE_STARTSTATE_NOTIFY1STATE_NOTIFY2STATE_REAPABLESTATE_IGNORESTATE_WHITELIST"

var _StateEnum_index = [...]uint8{0, 11, 24, 37, 51, 63, 78}

func (i StateEnum) String() string {
	if i < 0 || i >= StateEnum(len(_StateEnum_index)-1) {
		return fmt.Sprintf("StateEnum(%d)", i)
	}
	return _StateEnum_name[_StateEnum_index[i]:_StateEnum_index[i+1]]
}
