// generated by stringer -type=StateEnum state; DO NOT EDIT

package state

import "fmt"

const _StateEnum_name = "InitialStateFirstStateSecondStateThirdStateFinalStateIgnoreState"

var _StateEnum_index = [...]uint8{0, 12, 22, 33, 43, 53, 64}

func (i StateEnum) String() string {
	if i < 0 || i >= StateEnum(len(_StateEnum_index)-1) {
		return fmt.Sprintf("StateEnum(%d)", i)
	}
	return _StateEnum_name[_StateEnum_index[i]:_StateEnum_index[i+1]]
}
