// generated by stringer -type=AWSState aws; DO NOT EDIT

package aws

import "fmt"

const _AWSState_name = "pendingrunningshuttingDownterminatedstoppingstopped"

var _AWSState_index = [...]uint8{0, 7, 14, 26, 36, 44, 51}

func (i AWSState) String() string {
	if i < 0 || i >= AWSState(len(_AWSState_index)-1) {
		return fmt.Sprintf("AWSState(%d)", i)
	}
	return _AWSState_name[_AWSState_index[i]:_AWSState_index[i+1]]
}
